import MSWBrowser from "mocks/msw";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { initMockServer } from "../mocks";
import "styles/globals.scss";
import Providers from "@components/providers";
import { getSession } from "lib/session";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

if (process.env.NODE_ENV === "development") {
    initMockServer();
}

export default async function RootLayout({
    children,
}: {
    children: React.ReactNode;
}) {
    const session = await getSession();

    return (
        <html lang="ko">
            <body className={inter.className}>
                <MSWBrowser />
                <Providers session={session}>
                    <main>{children}</main>
                </Providers>
            </body>
        </html>
    );
}
