import MSWBrowser from "mocks/msw";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { initMockServer } from "../mocks";
import "styles/globals.scss";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

if (process.env.NODE_ENV === "development") {
    initMockServer();
}

export default function RootLayout({
    children,
}: {
    children: React.ReactNode;
}) {
    return (
        <html lang="ko">
            <body className={inter.className}>
                <MSWBrowser />
                <main>{children}</main>
            </body>
        </html>
    );
}
